### ISSUE TITLE
IT'S TOO LOUD

### ISSUE THREAD

**Issue by jhobz** [joakin/stack#1]

**Comment by joakin** [comment]
- [x] Add volume slider (input type range) somewhere (to the right of add form?)

**Comment by kodchi** [comment]
- [ ] default volume should be 0.
- [ ] push and pop sounds should be different.

**Comment by bd808** [comment]
Apparently default volume for html5 audio is `1.0` which represents the max possible volume.

**Comment by joakin** [comment]
Yeah, I tried lowering it with `volume='0.3'` on the audio tags I'm cloning but it seems like the volume won't get cloned. I'll try it out later again.
- [ ] Add volume slider
- [x] Default non-muted volume to 0.2 or 0.3

**Comment by joakin** [comment]
Alright default volume is 5% (0.05) now. it turns out cloning the dom node didn't copy the volume attribute... See https://github.com/joakin/stack/commit/94a8c1e602fc7f0f9fd3659350fa296b959ff939
