### ISSUE TITLE
As a participant new to STACK'ing, I need clearer language, because “Push” and “Stack” and “Pop” don’t mean much to me.

### ISSUE THREAD

**Issue by mbinder-wmf** [joakin/stack#10]

**Comment by joakin** [comment]
Suggestions welcome! (Really)

I can set [this](http://www.csit.parkland.edu/~mbrandyberry/CS2Java/Lessons/Stack_Queue/images/QueuePushPop.jpg) as the background :stuck_out_tongue_closed_eyes: 

![stack](http://www.csit.parkland.edu/~mbrandyberry/CS2Java/Lessons/Stack_Queue/images/QueuePushPop.jpg)

**Comment by mbinder-wmf** [comment]
Ha, that certainly helps with the language, but what if we just used "Queue" (instead of "Stack") and "Raise Hand" or "Add me to the queue" (instead of "Push") and "Next Participant" (instead of "Pop)?

**Comment by joakin** [comment]
Fixed, check it out to see if it's clearer @mbinder-wmf (http://stack.wmflabs.org/ & http://stack.wmflabs.org/room/stack)

**Comment by mbinder-wmf** [comment]
I think this is better. "Remove participant" is a little unclear, though. My inclination is that pressing that will allow me to choose a name to remove. It's not totally clear it just means "next in line."

**Comment by joakin** [comment]
Will rename to _Next participant_ as part of #3
