### ISSUE TITLE
As a participant, I want to see who "has the floor," so I know not only who is next but also whom they are after.

### ISSUE THREAD

**Issue by mbinder-wmf** [joakin/stack#3]
One suggestion was to have this information between where a name is entered and where a name is removed (currently "push" and "pop").

**Comment by joakin** [comment]
So, does _has the floor_ mean who is currently speaking? Isn't that the first person on the stack?

What exactly would you want to see, last person popped?

Thanks for all the issues :wink:

**Comment by mbinder-wmf** [comment]
Yea, I think it was suggested that we could show who is next (the top of the stack) and who is speaking, separately. "Last person popped" sounds good to me.

**Comment by joakin** [comment]
@mbinder-wmf @KristenLans Would something like this work? I'm planning to do some work on it this weekend.

```
Queue
[_______] has the floor            [[Next participant]]
1. Max
2. Kristen
3. Joaquin
```

Clicking `Next participant` would perform the following change:

```
Queue
[Max] has the floor            [[Next participant]]
1. Kristen
2. Joaquin
```

Clicking `Next participant` again would remove max and assign the next one there:

```
Queue
[Kristen] has the floor            [[Next participant]]
1. Joaquin
```

**Comment by mbinder-wmf** [comment]
looks reasonable to me
