### ISSUE TITLE
As a participant, it's not clear to me who controls "pop."

### ISSUE THREAD

**Issue by mbinder-wmf** [joakin/stack#9]
Users weren't sure if they popped themselves, or the facilitator did that.

**Comment by joakin** [comment]
Yep. We've collaboratively done this and it hasn't been much of a problem, but I agree that it can be.

Would a checkbox like Hatjitsu's `[x] I'm a facilitator` work? It would show the `Pop` and reordering controls among other things we consider of the facilitator role.

**Comment by joakin** [comment]
See #12
